### ISSUE TITLE
Writing Functional requirements

### ISSUE THREAD

**Issue by qlynn** [qlynn/HRProject#1]
write functional requirements
related task: #2

**Comment by qlynn** [comment]
comment

**Comment by qlynn** [comment]
@MishaPishniy please take into account this document from client: http://address.com/documents/doc.pdf

**Comment by Tizoo7** [comment]
#2

**Comment by MishaPishniy** [comment]
1) Сохранять информацию о клиентах в файл
2) Выводить информацию о клиентах на экран

**Comment by MishaPishniy** [comment]
@qlynn please review

**Comment by qlynn** [comment]
all OK
