### ISSUE TITLE
Create UML diagrams

### ISSUE THREAD

**Issue by qlynn** [qlynn/HRProject#3]

**Comment by Quasar21** [comment]
Done!
Use case diagram - https://someurl.com/usecase.diagram
State diagram - https://someurl.com/state.diagram
Class diagram - https://someurl.com/class.diagram
Component diagram - https://someurl.com/component.diagram
Deployment diagram - https://someurl.com/deployment.diagram

**Comment by qlynn** [comment]
@Quasar21 Sequence diagrams are missing

**Comment by Quasar21** [comment]
No, it's right here https://someurl.com/sequence.diagram
Sorry, I've forgotten to write it down

**Comment by qlynn** [comment]
all OK
